"""Shared deterministic inference boundary for universal RuleMatch values."""

from systems.Parasara.engine.inference.config import (
    InferenceConfig,
    inference_config_logical_json_bytes,
    inference_config_logical_sha256,
    inference_config_to_data,
    load_inference_config,
)
from systems.Parasara.engine.inference.engine import InferenceEngine
from systems.Parasara.engine.inference.models import (
    CapabilityAvailability,
    ConflictRecord,
    ConflictSide,
    Contribution,
    ContributionSign,
    DataCompleteness,
    EvidenceReference,
    ExplanationFactor,
    InferenceCompatibilityProjection,
    InferenceComponent,
    InferenceError,
    InferenceResult,
    InferenceStatus,
    TimingContext,
    inference_model_logical_json_bytes,
    inference_model_to_logical_data,
    inference_result_from_logical_data,
    inference_result_from_logical_json,
    inference_result_logical_json_bytes,
    inference_result_logical_sha256,
    inference_result_to_logical_data,
)

__all__ = (
    "CapabilityAvailability",
    "ConflictRecord",
    "ConflictSide",
    "Contribution",
    "ContributionSign",
    "DataCompleteness",
    "EvidenceReference",
    "ExplanationFactor",
    "InferenceCompatibilityProjection",
    "InferenceComponent",
    "InferenceConfig",
    "InferenceEngine",
    "InferenceError",
    "InferenceResult",
    "InferenceStatus",
    "TimingContext",
    "inference_config_logical_json_bytes",
    "inference_config_logical_sha256",
    "inference_config_to_data",
    "inference_model_logical_json_bytes",
    "inference_model_to_logical_data",
    "inference_result_from_logical_data",
    "inference_result_from_logical_json",
    "inference_result_logical_json_bytes",
    "inference_result_logical_sha256",
    "inference_result_to_logical_data",
    "load_inference_config",
)
