import "../styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="site-header">
          <div className="page-container flex items-center justify-between">
            <div>
              <div className="site-title">Jyothishyam</div>
              <div className="site-sub">Vedic astrology, reimagined</div>
            </div>
            <nav className="hidden sm:flex gap-4 items-center">
              <a href="/login" className="text-text-muted hover:text-text-primary">Log in</a>
              <a href="/register" className="btn-primary">Get started</a>
            </nav>
          </div>
        </header>

        <main className="min-h-[calc(100vh-72px)] flex items-center justify-center">
          <div className="page-container w-full">{children}</div>
        </main>
      </body>
    </html>
  )
}
