"""Scan repository for Markdown files and generate Documentation/ALL_DOCS_TOC.md

This script excludes the virtualenv, .git, node_modules and Documentation/ALL_DOCS_TOC.md itself.
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'Documentation' / 'ALL_DOCS_TOC.md'

EXCLUDE_DIRS = {'.git', 'node_modules', '__pycache__', 'jyothishyam_env'}

def is_md(p: Path):
    return p.suffix.lower() == '.md'

docs = []
for dirpath, dirnames, filenames in os.walk(ROOT):
    # skip exclude dirs
    parts = set(Path(dirpath).parts)
    if parts & EXCLUDE_DIRS:
        continue
    for fname in filenames:
        if not fname.lower().endswith('.md'):
            continue
        fp = Path(dirpath) / fname
        # skip the generated file itself
        if fp.resolve() == OUT.resolve():
            continue
        rel = fp.relative_to(ROOT)
        docs.append(rel.as_posix())

docs.sort()

with open(OUT, 'w', encoding='utf8') as f:
    header = """# All Markdown Documentation
This file is generated by `scripts/generate_docs_toc.py`.

"""
    f.write(header)
    for d in docs:
        f.write(f'- [{d}]({d})\n')

print('Wrote', OUT)
