"""Scan repository for Markdown files and generate Documentation/ALL_DOCS_TOC.md

This script excludes development artifacts, dependency folders, live Parāśara
stage workspaces, and Documentation/ALL_DOCS_TOC.md itself.
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'Documentation' / 'ALL_DOCS_TOC.md'

EXCLUDE_DIRS = {
    '.git',
    '.agents',
    '.codex',
    '.pytest_cache',
    '.venv',
    'node_modules',
    '__pycache__',
    'jyothishyam_env',
    'venv',
}
EXCLUDE_PREFIXES = {Path('systems/Parasara/Documentation/Engine')}

def is_md(p: Path):
    return p.suffix.lower() == '.md'

docs = []
for dirpath, dirnames, filenames in os.walk(ROOT):
    # skip exclude dirs
    parts = set(Path(dirpath).parts)
    if parts & EXCLUDE_DIRS:
        continue
    for fname in filenames:
        if not fname.lower().endswith('.md'):
            continue
        fp = Path(dirpath) / fname
        # skip the generated file itself
        if fp.resolve() == OUT.resolve():
            continue
        rel = fp.relative_to(ROOT)
        if any(rel == prefix or prefix in rel.parents for prefix in EXCLUDE_PREFIXES):
            continue
        docs.append(rel.as_posix())

docs.sort()

with open(OUT, 'w', encoding='utf8') as f:
    header = """# All Markdown Documentation
This file is generated by `scripts/generate_docs_toc.py`.

"""
    f.write(header)
    for d in docs:
        target = os.path.relpath(ROOT / d, OUT.parent).replace(os.sep, '/')
        f.write(f'- [{d}]({target})\n')

print('Wrote', OUT)
